tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "cask"
brew "jq"
brew "mas"
brew "starship"

cask "1password"
cask "google-chrome"
cask "iglance"
cask "iterm2"
cask "karabiner-elements"
cask "notion"
cask "readdle-spark"
cask "rectangle"
cask "spotify"
cask "visual-studio-code"

mas "Amphetamine", id: 937984704
mas "Keynote", id: 409183694
mas "Pages", id: 409201541
mas "카카오톡", id: 869223134
